Euroleague/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^Home/', include('Home.urls')),
    url(r'^standings/', include('standings.urls')),
    url(r'^stats/', include('stats.urls')),
    url(r'^roster/', include('roster.urls')),
    url(r'^players/', include('players.urls')),
    url(r'^videos/', include('videos.urls')),
    url(r'^About/', include('About.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Home/urls.py
from django.conf.urls import url
from . import views

app_name = 'Home'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^register/$', views.UserFormView.as_view(), name='register'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

]

players/urls.py
from django.conf.urls import url
from . import views

app_name = 'players'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^players/add/$', views.AddPlayer.as_view(), name='add-player'),
    url(r'^players/(?P<pk>[0-9]+)/delete/$', views.DeletePlayer.as_view(), name='delete-player'),


]

players/models.py
from django.db import models
from django.core.urlresolvers import reverse
class Player(models.Model):
    player_name = models.CharField(max_length=200)
    player_face = models.FileField()
    player_position = models.CharField(max_length=200)
    player_nationality = models.CharField(max_length=200)
    date_of_birth = models.CharField(max_length=200)
    player_team = models.CharField(max_length=200)
    player_height = models.CharField(max_length=200)



    def get_absolute_url(self):
        return reverse('players:detail', kwargs={'pk' : self.pk})

    def __str__(self):
        return self.player_name


class Stat(models.Model):
    stats = models.ForeignKey(Player, on_delete=models.CASCADE)
    games_played = models.DecimalField(decimal_places=0, max_digits=2)
    games_started = models.DecimalField(decimal_places=0, max_digits=2)
    minutes = models.CharField(max_length=200)
    points = models.DecimalField(decimal_places=1, max_digits=6)
    two_point = models.CharField(max_length=200)
    three_point = models.CharField(max_length=200)
    free_throw = models.CharField(max_length=200)
    rebounds = models.DecimalField(decimal_places=1, max_digits=6)
    assists =  models.DecimalField(decimal_places=1, max_digits=6)
    steals = models.DecimalField(decimal_places=1, max_digits=6)
    turnovers = models.DecimalField(decimal_places=1, max_digits=6)
    blocks = models.DecimalField(decimal_places=1, max_digits=6)
    index = models.DecimalField(decimal_places=1, max_digits=6)

    def __str__(self):
        return self.minutes

players/views.py
from django.views import generic
from .models import Player
from django.views.generic.edit import CreateView,DeleteView
from django.core.urlresolvers import reverse_lazy


class IndexView(generic.ListView):

    template_name = 'players/index.html'

    def get_queryset(self):
        return Player.objects.all()


class DetailView(generic.DetailView):
    model = Player
    template_name = 'players/detail.html'

class AddPlayer(CreateView) :
    model = Player
    fields = ['player_name','player_face','player_position','player_nationality','date_of_birth','player_team','player_height']

class DeletePlayer(DeleteView):
    model = Player
    success_url = reverse_lazy('players:index')

players/templates/players/detail.html
{% extends 'Home/base.html' %}
<title>{% block title %}Player stats{% endblock %}</title>
{% block players_active %}active{% endblock %}
{% block body %}
<div class="container-fluid container">

    <div class="row">


        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <br class="panel-body">
                    <a href="{% url 'players:detail' player.id %}">
                        {% if player.player_face %}
                            <img src="{{ player.player_face.url }}" class="img-responsive">

                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>


                </div>
                        <h4>Name : {{ player.player_name }}</h4>
                        <h4>Team : {{ player.player_team }}</h4>
                        <h4>Position : {{ player.player_position }}</h4>
                        <h4>Height : {{ player.player_height }}</h4>
                        <h4>Nationality : {{ player.player_nationality }}</h4>
                        <h4>Born : {{ player.date_of_birth }}</h4>



            </div>
        </div>

        <div class="col-sm-8 col-md-9">





                    <h3>{{player.player_name}}</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>GP</th>
                            <th>GS</th>
                            <th>Minutes</th>
                            <th>Points</th>
                            <th>2pt%</th>
                            <th>3pt%</th>
                            <th>FT%</th>
                            <th>Rebounds</th>
                            <th>Assists</th>
                            <th>Steals</th>
                            <th>Turnovers</th>
                            <th>Blocks</th>
                            <th>Index</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for stat in player.stat_set.all %}
                            <tr>
                                <td>{{ stat.games_played }}</td>
                                <td>{{ stat.games_started }}</td>
                                <td>{{ stat.minutes }}</td>
                                <td>{{ stat.points }}</td>
                                <td>{{ stat.two_point }}</td>
                                <td>{{ stat.three_point }}</td>
                                <td>{{ stat.free_throw }}</td>
                                <td>{{ stat.rebounds }}</td>
                                <td>{{ stat.assists }}</td>
                                <td>{{ stat.steals }}</td>
                                <td>{{ stat.turnovers }}</td>
                                <td>{{ stat.blocks }}</td>
                                <td>{{ stat.index }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>




{% endblock %}

players/templates/players/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <span class="text-danger small">{{field.errors}}</span>
        </div>
        <label class="control-label col-md-2">{{field.label_tag}}</label>
        <div class="col-md-10">{{field}}</div>
    </div>
{% endfor %}

players/templates/players/index.html
{% extends 'Home/base.html' %}
<title>{% block title %}Players Page{% endblock %}</title>
{% block players_active %}active{% endblock %}
{% block body %}

         <div class="container container-fluid">
           <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'players:index' %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
           <br><br><br>

             {% for player in object_list %}

                <div class="col-sm-4 col-lg-8">
                    <div class="thumbnail">
                        <a href="{% url 'players:detail' player.id %}">
                         <h3>{{ player.player_name }}({{player.player_team}})<form action="{% url 'players:delete-player' player.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="player_id" value="{{ player.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form></h3>
                        </a>


                </div>
            </div>


        {% endfor %}

             
</div>
{% endblock %}

players/templates/players/player_form.html
{% extends 'Home/base.html' %}
<title>{% block title %}Player add{% endblock %}</title>
{% block players_active %}active{% endblock %}

{% block body %}
   <div class="container fluid">
       <div class="row">
       <div class="col-md-12 col-lg-7">
           <div class="panel panel-default">
               <div class="panel-body">
                   <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                       {% csrf_token %}
                       {% include 'players/form-template.html' %}
                       <div class="form-group">
                           <div class="col-md-offset-2 col-md-10">
                               <button type="submit" class="btn btn-success">Submit</button>

                           </div>

                       </div>
                   </form>

               </div>

           </div>
       </div>
       </div>
   </div>
{% endblock %}