About/urls.py
from django.conf.urls import url
from . import views

app_name = 'About'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),

]

Euroleague/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^Home/', include('Home.urls')),
    url(r'^standings/', include('standings.urls')),
    url(r'^stats/', include('stats.urls')),
    url(r'^roster/', include('roster.urls')),
    url(r'^players/', include('players.urls')),
    url(r'^videos/', include('videos.urls')),
    url(r'^About/', include('About.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Home/urls.py
from django.conf.urls import url
from . import views

app_name = 'Home'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^register/$', views.UserFormView.as_view(), name='register'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

]

roster/urls.py
from django.conf.urls import url
from . import views

app_name = 'roster'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

]

stats/urls.py
from django.conf.urls import url
from . import views

app_name = 'stats'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),

]

videos/urls.py
from django.conf.urls import url
from . import views

app_name = 'videos'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^videos/add/$', views.AddVideo.as_view(), name='add-video'),
    url(r'^videos/(?P<pk>[0-9]+)/delete/$', views.DeleteVideo.as_view(), name='delete-video'),

]

Home/models.py
from django.db import models


class Round(models.Model):
    round_number = models.CharField(max_length=20)
    round_picture = models.FileField()

    def __str__(self):
        return self.round_number


class Video(models.Model):
    round = models.ForeignKey(Round, on_delete=models.CASCADE)
    video_file = models.FileField()
    video_name = models.CharField(max_length=2000)

    def __str__(self):
        return self.video_name

Home/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username', 'email', 'password']

Home/views.py
from django.views import generic
from .models import Round,Video
from django. shortcuts import render, redirect
from django.contrib.auth import authenticate,login
from django.views.generic import  View
from .forms import UserForm



class IndexView(generic.ListView):
    template_name = 'Home/index.html'

    def get_queryset(self):
        return Round.objects.all()


class DetailView(generic.DetailView):
    model = Round
    template_name = 'Home/detail.html'


class UserFormView(View):
    form_class = UserForm
    template_name = 'Home/registration_form.html'

    def get(self,request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form' : form})
    def post(self,request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)

            username =form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('Home:index')


        return render(request, self.template_name, {'form': form})

Home/templates/Home/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Home Page{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'Home/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-inverse ">
   <div class="container-fluid">
       <div class="navbar-header">
           <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>
           </button>
           <a href="#" class="navbar-brand">Euroleague website</a>
       </div>


           <div class="collpapse navbar-collapse" id="topNavBar">
               <ul class="nav navbar-nav " >
                   <li class="{% block Home_active %}{% endblock %}"><a href="{% url 'Home:index' %}">
                       <span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp;Home</a> </li>
                   <li class="{% block standings_active %}{% endblock %}"><a href="{% url 'standings:index' %}">
                       <span class="glyphicon glyphicon-list" aria-hidden="true"></span>Standings</a> </li>
                   <li class="{% block stats_active %}{% endblock %}"><a href="{% url 'stats:index' %}">
                       <span class="glyphicon glyphicon-stats" aria-hidden="true"></span>Stats</a> </li>
                   <li class="{% block roster_active %}{% endblock %}"><a href="{% url 'roster:index' %}">Roster</a> </li>
                   <li class="{% block players_active %}{% endblock %}"><a href="{% url 'players:index' %}">
                       <span class="glyphicon glyphicon-user" aria-hidden="true"></span>Players</a> </li>
                   <li class="{% block videos_active %}{% endblock %}"><a href="{% url 'videos:index' %}">
                        <span class="glyphicon glyphicon-facetime-video" aria-hidden="true"></span>Videos</a> </li>
                   <li class="{% block About_active %}{% endblock %}"><a href="{% url 'About:index' %}">
                        About</a> </li>
                    <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;Add</a>
                        <ul class="dropdown-menu">
                            <li >><a href="{% url 'players:add-player' %}">
                                <span class="glyphicon glyphicon-user" aria-hidden="true"></span>Player</a></li>
                            <li >><a href="{% url 'videos:add-video' %}">
                                <span class="glyphicon glyphicon-facetime-video" aria-hidden="true"></span>Video</a></li>
                        </ul>
                </li>
               </ul>


           </div>
       </div>
   </nav>
{% block body %}
{% endblock %}
</body>
</html>

Home/templates/Home/detail.html
{% extends 'Home/base.html' %}
{% block title %}Game highlights{% endblock %}
{% block Home_active %}active{% endblock %}
{% block body %}

   <div class="container">

         <table class = 'table' >
             <thead>
             <tr>
                 <th>Name</th>
                 <th>Video</th>
             </tr>
             </thead>
             <tbody>
             {% for video in round.video_set.all %}
             <tr>
                 <td><h3>{{video.video_name}}</h3></td>
                 <td><video controls="" height="240" width="320">
                    <source src="{{ video.video_file.url}}" type="video/mp4" />
                 </video>
                     </td>
             </tr>
             {% endfor %}
             </tbody>
         </table>
     </div>

{% endblock %}

Home/templates/Home/index.html
{% extends 'Home/base.html' %}
{% block Home_active %}active{% endblock %}
{% block body %}

         <div class="container container-fluid">
             {% for round in object_list %}

                <div class="col-sm-4 col-lg-8">

                        <a href="{% url 'Home:detail' round.id %}">
                         <h3>{{ round.round_number }}</h3>
                        </a>



            </div>


        {% endfor %}


</div>
{% endblock %}

Home/templates/Home/registration_form.html
{% extends 'Home/base.html' %}
{% block title %}Register{% endblock %}


{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Register for an Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'players/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>

</div>

{% endblock %}