Euroleague/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^Home/', include('Home.urls')),
    url(r'^standings/', include('standings.urls')),
    url(r'^stats/', include('stats.urls')),
    url(r'^roster/', include('roster.urls')),
    url(r'^players/', include('players.urls')),
    url(r'^videos/', include('videos.urls')),
    url(r'^About/', include('About.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Home/urls.py
from django.conf.urls import url
from . import views

app_name = 'Home'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^register/$', views.UserFormView.as_view(), name='register'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

]

roster/urls.py
from django.conf.urls import url
from . import views

app_name = 'roster'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

]

roster/models.py
from django.db import models
from django.core.urlresolvers import reverse
class Team(models.Model):
    team_name = models.CharField(max_length=200)
    team_logo = models.FileField()
    city = models.CharField(max_length=200)
    city_image = models.FileField()
    arena = models.CharField(max_length=200)
    arena_image = models.FileField()

    def get_absolute_url(self):
        return reverse('roster:detail', kwargs={'pk' : self.pk})

    def __str__(self):
        return self.team_name


class Person(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    person_number = models.CharField(max_length=3)
    person_name = models.CharField(max_length=200)
    person_position = models.CharField(max_length=50)
    person_image = models.FileField()
    person_age = models.CharField(max_length=2)

    def __str__(self):
        return self.person_name

roster/views.py
from django.views import generic
from .models import Team,Person


class IndexView(generic.ListView):
    template_name = 'roster/index.html'

    def get_queryset(self):
        return Team.objects.all()


class DetailView(generic.DetailView):
    model = Team
    template_name = 'roster/detail.html'

roster/templates/roster/detail.html
{% extends 'Home/base.html' %}
<title>{% block title %}{{team.team_name}} roster{% endblock %}</title>
{% block roster_active %}active{% endblock %}
{% block body %}
<div class="container-fluid container">

    <div class="row">


        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <br class="panel-body">
                    <a href="{% url 'roster:detail' team.id %}">
                        {% if team.team_logo %}
                        <h1>{{ team.team_name }}</h1>
                            <img src="{{ team.team_logo.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a></br>
                    <img src="{{ team.arena_image.url }}" class="img-responsive">
                        <h3>{{team.arena}}</h3>
                </div>
            </div>
        </div>


        <div class="col-sm-8 col-md-9">



            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>{{team.team_name}} players and coach</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>Number</th>
                            <th>Name</th>
                            <th>Position</th>
                            <th>Age</th>
                            <th>Face</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for person in team.person_set.all %}
                            <tr>
                                <td>{{ person.person_number }}</td>
                                <td>{{ person.person_name }}</td>
                                <td>{{ person.person_position }}</td>
                                <td>{{ person.person_age }}</td>
                                <td><img src="{{ person.person_image.url }}" class="img-responsive"></td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

roster/templates/roster/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <span class="text-danger small">{{field.errors}}</span>
        </div>
        <label class="control-label col-md-2">{{field.label_tag}}</label>
        <div class="col-md-10">{{field}}</div>
    </div>
{% endfor %}

roster/templates/roster/index.html
{% extends 'Home/base.html' %}
<title>{% block title %}Teams page{% endblock %}</title>
{% block roster_active %}active{% endblock %}
{% block body %}
         <div class="container container-fluid">
             {% for team in object_list %}
                <div class="col-md-4 col-md-2">
                    <div class="thumbnail">
                        <h5>{{ team.team_name }}</h5>
                        <a href="{% url 'roster:detail' team.id %}">

                            <img src="{{ team.team_logo.url }}" class="img-responsive">
                        </a>
                        <div class="caption">

                             <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{% url 'roster:detail' team.id %}">Team page</a></li>
            </ul>

                            </div>
                </div>
            </div>

        {% endfor %}

</div>
{% endblock %}

roster/templates/roster/team_form.html
{% extends 'Home/base.html' %}



{% block body %}
   <div class="container fluid">
       <div class="row">
       <div class="col-md-12 col-lg-7">
           <div class="panel panel-default">
               <div class="panel-body">
                   <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                       {% csrf_token %}
                       {% include 'roster/form-template.html' %}
                       <div class="form-group">
                           <div class="col-md-offset-2 col-md-10">
                               <button type="submit" class="btn btn-success">Submit</button>

                           </div>

                       </div>
                   </form>

               </div>

           </div>
       </div>
       </div>
   </div>
{% endblock %}