Euroleague/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^Home/', include('Home.urls')),
    url(r'^standings/', include('standings.urls')),
    url(r'^stats/', include('stats.urls')),
    url(r'^roster/', include('roster.urls')),
    url(r'^players/', include('players.urls')),
    url(r'^videos/', include('videos.urls')),
    url(r'^About/', include('About.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Home/urls.py
from django.conf.urls import url
from . import views

app_name = 'Home'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^register/$', views.UserFormView.as_view(), name='register'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

]

roster/urls.py
from django.conf.urls import url
from . import views

app_name = 'roster'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

]

standings/urls.py
from django.conf.urls import url
from . import views

app_name = 'standings'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),


]

standings/models.py
from django.db import models


class Table (models.Model):
    name = models.CharField(max_length=20)


    def __str__(self):
        return self.name

standings/views.py
from django.views import generic
from .models import Table




class IndexView(generic.ListView):
    template_name = 'standings/index.html'

    def get_queryset(self):
        return Table.objects.all()

standings/templates/standings/index.html
{% extends 'Home/base.html' %}
<title>{% block title %}Standings{% endblock %}</title>
{% block standings_active %}active{% endblock %}
{% block body %}
<div class="container container-fluid">
    {% for table in object_list %}

        <h1>{{table.name}}</h1>
        <div class="container">
            <table class="table">
                <thead>
                <tr>
                    <th>Pos</th>
                    <th>Name</th>
                    <th>GP</th>
                    <th>W</th>
                    <th>L</th>
                    <th>PS</th>
                    <th>PA</th>
                    <th>+/-</th>
                    <th>Points</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>1.</td><td><a href="{% url 'roster:detail' 6 %}">CSKA Moscow</a></td><td>26</td><td>21</td><td>5</td><td>2331</td><td>2057</td><td>+274</td><td>42</td>
                </tr>
                 <tr>
                     <td>2.</td><td><a href="{% url 'roster:detail' 11 %}">Olympiakos</a></td><td>26</td><td>18</td><td>8</td><td>1944</td><td>1925</td><td>+19</td><td>36</td>
                </tr>
                <tr>
                    <td>3.</td><td><a href="{% url 'roster:detail' 8 %}">Fenerbahce Dogus Istanbul </a></td><td>26</td><td>18</td><td>8</td><td>2058</td><td>1925</td><td>+133</td><td>36</td>
                </tr>
                   <tr>
                     <td>4.</td><td><a href="{% url 'roster:detail' 13 %}">Real Madrid</a></td><td>26</td><td>16</td><td>10</td><td>2212</td><td>2033</td><td>+179</td><td>32</td>
                </tr>
                 <tr>
                    <td>5.</td><td><a href="{% url 'roster:detail' 9 %}">Khimki Moskov Region</a></td><td>26</td><td>15</td><td>11</td><td>2034</td><td>2030</td><td>+4</td><td>30</td>
                </tr>
                  <tr>
                    <td>6.</td><td><a href="{% url 'roster:detail' 12 %}">Panathinaikos</a></td><td>26</td><td>15</td><td>11</td><td>2005</td><td>2002</td><td>+3</td><td>30</td>
                </tr>
                <tr>
                  <td>7.</td><td><a href="{% url 'roster:detail' 16 %}">Zalgiris Kaunas</a></td><td>26</td><td>15</td><td>11</td><td>2094</td><td>2083</td><td>+11</td><td>30</td>
                </tr>
                <tr>
                    <td>8.</td><td><a href="{% url 'roster:detail' 3 %}">Baskonia Vitoria Gasteiz</a></td><td>26</td><td>13</td><td>13</td><td>2136</td><td>2068</td><td>+68</td><td>26</td>
                </tr>
                <tr>
                    <td>9.</td><td><a href="{% url 'roster:detail' 10 %}">Macabi Tel Aviv</a></td><td>26</td><td>13</td><td>13</td><td>2136</td><td>2197</td><td>-61</td><td>26</td>
                </tr>
                <tr>
                     <td>10.</td><td><a href="{% url 'roster:detail' 5 %}">Crvena Zvezda mts</a></td><td>26</td><td>11</td><td>15</td><td>2039</td><td>2170</td><td>-131</td><td>22</td>
                </tr>
                <tr>
                    <td>11.</td><td><a href="{% url 'roster:detail' 15 %}">Unicaja Malaga</a></td><td>26</td><td>10</td><td>16</td><td>2007</td><td>2094</td><td>-87</td><td>20</td>
                </tr>
                 <tr>
                     <td>12.</td><td><a href="{% url 'roster:detail' 4 %}">Brose Bamberg</a></td><td>26</td><td>10</td><td>16</td><td>1973</td><td>2066</td><td>-93</td><td>20</td>
                </tr>
                <tr>
                    <td>13.</td><td><a href="{% url 'roster:detail' 7 %}">Barcelona Lassa</a></td><td>26</td><td>9</td><td>17</td><td>2099</td><td>2058</td><td>+41</td><td>18</td>
                </tr>
                  <tr>
                  <td>14.</td><td><a href="{% url 'roster:detail' 15 %}">Valencia Basket</a></td><td>26</td><td>9</td><td>17</td><td>2004</td><td>2084</td><td>-80</td><td>18</td>
                </tr>
                 <tr>
                    <td>15.</td><td><a href="{% url 'roster:detail' 2 %}">AX Armani Exchange Olimpia Milano</a></td><td>26</td><td>9</td><td>17</td><td>2083</td><td>2195</td><td>-112</td><td>18</td>
                </tr>
                <tr>
                    <td>16.</td><td><a href="{% url 'roster:detail' 1 %}">Anadolu Efes Istanbul</a></td><td>26</td><td>6</td><td>20</td><td>2002</td><td>2170</td><td>-168</td><td>12</td>
                </tr>



                </tbody>
            </table>
        </div>

              <h6>Pos=position</h6>
              <h6>GP=games played</h6>
              <h6>W=games won</h6>
              <h6>L=games lost</h6>
              <h6>PS=points scored</h6>
              <h6>PA=points allowed</h6>
              <h6>+/-=points diferential</h6>

{% endfor %}
</div>


{% endblock %}